### ISSUE TITLE
Issue Plugin is crashing itself

### ISSUE THREAD

**Issue by NikeSchuh** [Indyuce/mmoitems#1]
Here is the whole log [21:46:03] is the Plugin crashing itself 
[2019-06-30-7.log](https://github.com/Indyuce/mmoitems/files/3344166/2019-06-30-7.log)
Another Issue with Sentinel and Citizens
Attacks are just flying throw npcs
https://pastebin.com/xSCHgHDq

**Comment by Indyuce** [comment]
Looks like a compatibility issue with SkillAPI, I will get that fixed in the next update which will be out really soon.

**Comment by NikeSchuh** [comment]
Is SpigotMc down?

**Comment by Indyuce** [comment]
Doesn't have anything to do with that issue, please don't go offtopic
