### ISSUE TITLE
heavy charge error 

### ISSUE THREAD

**Issue by slvlr** [Indyuce/mmoitems#102]
**Describe the bug**

**To Reproduce**
1. Right click a shield with the ability Heavy Charge (Shift right click)
2. Error https://pastebin.com/jWBui7GE

**Expected behavior**
Heavy charge

**Server info:**
 - Tuinity 1.15.2
 - MMOItems 5.4.2

**Additional context**
https://pastebin.com/jWBui7GE

**Comment by Darwin1546** [comment]
All consumables broken in 5.4.2

**Comment by slvlr** [comment]
All abilities consumable or not seem to be broken.
