### ISSUE TITLE
Custom Durability use Vanilla Durability System

### ISSUE THREAD

**Issue by khanhtung74** [Indyuce/mmoitems#105]
**Describe the bug**
 When MMOItems introduce the custom durability use the vanilla systems, I think it really cool, now my player did not need to view the durability by open inventory, then inspect the items .

But because the item change vanilla durability, the item will change the custom model, it will fix in 1.14+, but my server in 1.13.2. The features are very nice, but I don't want to upgrade all the servers to the new version because I can't use any new mmoitems build

Since it is a new feature, can you add an option to turn of it? I really want to use new mmoitems build

**To Reproduce**
Make an item have durability and unbreakable 
Attack with this item
Item change model

**Server info:**
 - Spigot Build & Version: 1.13.2 Lastest
 - Plugin Version: All MMOItems 5.3+ build

**Comment by Indyuce** [comment]
Our priority is to provide the max amount of stable features for the latest versions of Minecraft. The old custom durability system was glitchy and unefficient overall so we moved it to the vanilla durability bar, it's a bad update for 1.13 users but we can't afford going back to the older system
