### ISSUE TITLE
Modifiy durability 1.14.3

### ISSUE THREAD

**Issue by Florianpal1** [Indyuce/mmoitems#12]
The custom durability system does not work if you want to add durability. Example: If we define the durability of an iron helmet to 250, the item will break after a loss of 165 of durability which is vanilla durability. But the system works well if you define a lower durability than vanilla. Our server is in 1.14.3 with a paperspigot version git-paper-129

**Comment by Indyuce** [comment]
An item which has custom durability does not automatically lose its vanilla durability. Although it's useless, an item can have both vanilla and custom durability at the same time. You can disable vanilla durability by using the `Unbreakable` item option which only applies for vanilla durability.
