### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by BrainRTP** [Indyuce/mmoitems#13]
<img width="809" alt="Снимок экрана 2019-07-14 в 20 22 02" src="https://user-images.githubusercontent.com/22731705/61185678-7c66b100-a675-11e9-85b7-3ea55704c45b.png">
Help me, please. I updated the plugin from 4.7.0 to 4.7.1

**Comment by Indyuce** [comment]
Use `MMOItems.plugin.setRPG(....)`
