### ISSUE TITLE
Vomit Skill bug

### ISSUE THREAD

**Issue by jayjay104** [Indyuce/mmoitems#14]
When using the vomit skill the rotten flesh that drops for short time is pickup able, i believe this is bug because it wasnt in last version and when picked up it takes up all ur space
![2019-07-15_23 56 53](https://user-images.githubusercontent.com/52924707/61223662-47815980-a75c-11e9-893b-0e7b8f5e696d.png)

**Comment by Indyuce** [comment]
Are you running the Legacy version?

**Comment by jayjay104** [comment]
pfff, updated to the latest version u posted a few minutes ago and it dosnt do it anymore so whatever but i was using the previous version from that before
