### ISSUE TITLE
Crafting Stations not working

### ISSUE THREAD

**Issue by Florianpal1** [Indyuce/mmoitems#18]
**Describe the bug**
The crafting stations are no longer loaded since the last version of the plugin. While an old test model that we had run in the previous version of the plugin, this same version of the crafting stations no longer works in version 4.7.2 of the plugin. And none of the basic models load.

**Screenshots**
![Captur1](https://user-images.githubusercontent.com/36370356/61594324-f5708600-abea-11e9-9510-ed6c909a3a4d.PNG)
![Capture](https://user-images.githubusercontent.com/36370356/61594326-f9040d00-abea-11e9-9055-6ccf8d807ca7.PNG)

**Server info:**
 - Paper 136 1.14.4
 - MMOItems 4.7.2

**Comment by Indyuce** [comment]
Will be fixed in the next update.

**Comment by Indyuce** [comment]
Sorry for reopening. I accidentally had to double post 4.7.3 the day it was out because of an issue which would disable basically any crafting station. Have you tried using the **very** latest version of MI available?

**Comment by Florianpal1** [comment]
Yes, the stations work in the latest version of Mmoitems. Thank you and sorry for the inconvenience.
