### ISSUE TITLE
Item Sharpening Not Working on SkillAPI Class Only Items

### ISSUE THREAD

**Issue by beratakdas** [Indyuce/mmoitems#25]
Same as title. When i use item sharpening consumable on skillapi class only item, passes the process.

**Comment by Indyuce** [comment]
What spigot, MI and SkillAPI builds are you running? What do you mean by "passes the process": do the item switch places in the inventory, or is there an error message displayed in the chat? Any error logs?

**Comment by beratakdas** [comment]
paper spigot 1.13.2, mmoitems 4.7.8, skillapi  1.89 

Displayed in chat "upgrade successfull" message but weapon and consumable remain. When I try consumable on another weapon without class requirement, works smoothly. The only difference between these two weapons is just class requirement.

**Comment by Indyuce** [comment]
Any console error logs?

**Comment by beratakdas** [comment]
No, not giving any console error.

**Comment by Indyuce** [comment]
Will check asap

**Comment by Indyuce** [comment]
Just replicated the bug on SkillAPI 1.89 and MMOItems 4.7.9, it threw a console log which is related to the Required Class item option. I'll get this issue fixed, next time please do double check your console.
