### ISSUE TITLE
how to set drop on only world

### ISSUE THREAD

**Issue by aatomant** [Indyuce/mmoitems#29]
There a ITEM DUPLICATING bug with our Towny plugin and MMOITEM plugin.
As normaly there is a chance to get MMO items from breaking blocks and when your in a Towny plugin world, you have to be in a town to break a block but when your out of the town you can't break anything.
But players still have a chance to get MMO items from breaking blocks out of a town when the block didn't actually break.

So what i'm wondering is how to turn off MMO drops in a Towny plugin world.

**Comment by Indyuce** [comment]
Will be fixed in the next update.

**Comment by aatomant** [comment]
and Throw item can DUPLICATING in hopper
