### ISSUE TITLE
Cant attack Npcs

### ISSUE THREAD

**Issue by NikeSchuh** [Indyuce/mmoitems#3]
I dont know why but every ability or ranged attack (particle based) flys throw npcs
There is no console error and no hint.
And melee weapons work but their Multipliers dont get applied (Dagger Base DMG : 10 + 200Dmg)
only deals 10 and not 30
Spigot Version : Spigot-dcd1643-e60fc34
Installed NPC Plugins : Sentinel,Citizens 2 (Free Version)

**Comment by Indyuce** [comment]
I tried running Citizens and MMOItems on 1.12, I couldn't get any staff to hit an NPC from Citizens.

What do you mean by _multipliers_?

**Comment by Indyuce** [comment]
Closing this issue till more info is provided
