### ISSUE TITLE
option for item to be udpated on certain hand(main | off ) 

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmoitems#36]
We clearly want marksman to shoot arrow, instead of holding bow at offhand and holding sword. Some supplement item ( like tome ) is supposed to be in offhand. Therefore, it might be nice to have some option that certain item must be in main or offhand to be updated.

**Comment by Indyuce** [comment]
I don't understand what you're trying to say

**Comment by aaa8881** [comment]
> I'm not sure I'm trying to understand what you are trying to say. Do you mean that bows should only apply their stats when worn in main hand only?

For me , yes , but maybe not for other people. I found "item type" has this kinda functionality yesterday. Also, documentation for item types is bit wrong too
```
Off-Catalysts (catalysts only apply their stats when held in main hand, off-catalysts also apply their stats on the off hand).
```
It says catalyst only applies .. on main hand, but it actually applies on off hand. Also, I'm not very sure if there's any item type that stats are updated only when item is in main hand. So like catalyst, it might be nice if there is parent item type like "mainhand_weapon" , so that player who want only-main-hand-weapon to set certain item type's parent to that itemType.

**Comment by Indyuce** [comment]
I might just add an option to change that in the future because of how it can be confusing... The wiki is indeed wrong on that, thanks for letting me know, will be fixed.
