### ISSUE TITLE
temporary buff for consumable item 

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmoitems#38]
It might be nice if there is temporary buff system for consumable. It may be applied to any MI attributes including damage, mana, or whatever that MI supports. 
For example , an item like "damage enhance potion" that provides 10 attack damage bonus for next 60 seconds.

**Comment by Indyuce** [comment]
It's planned. With the development of MMOCore I have slowly been implementing all the API changes required for that type of system.
