### ISSUE TITLE
Consumable does not get consumed on certain condition

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmoitems#39]
Consumable item does not disappear when the command it is attached gives item to player's inventory. This can be avoided by setting delay to non zero, so not a very big issue - still possible dupe for people who didn't find this out - and can suffer some other users later.

**Comment by Indyuce** [comment]
Please send the item config used so I can reproduce it on my end.

**Comment by Indyuce** [comment]
Closed till further info is provided
