### ISSUE TITLE
Item recognition in advanced crafting

### ISSUE THREAD

**Issue by Niko302** [Indyuce/mmoitems#4]
**Describe the bug**
When I changed from 1.12 to 1.14.2 I had to change a couple of config files but when you try to make a new item and put it in the crafting grid if the item is named it does show up when you are making the recipe but when viewing it from shift-clicking the crafting table the item shows as default.
1.12 version on the server:
https://imgur.com/8PhXpwv

1.14.2 version of the server when crafting:
https://imgur.com/a/w01gR9z

1.14.2 version on the server when viewing recipe:
https://imgur.com/hp2gpYM

**To Reproduce**
create item, look at the item in the recipe book.

**Expected behavior**
Item has a nametag

**Comment by Indyuce** [comment]
Got it. It will be fixed in the next update.
