### ISSUE TITLE
Item regeneration stat is applying in undesirable way. 

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmoitems#40]
Item regeneration stat is supposed to be increased by percentage of whatever regeneration that player has. 

Once health regeneration event is fired( or foodLevel change or whatever that is account of ) , minecraft's default level of regeneration is 1 heart in every 5 seconds. 

Hence, health regeneration stat of 50% should make this regneration to 1.5 heart in every 5 seconds , as that is what 50% increment means. 

However, it seems like it regenerate 50 health ( or whatever , at least it's not 1.5 heart ) , that makes player to regenerate to full health in a blink. 

----------------
MI health regeneration should also consider the health-regen of MMOCORE , so that it applies to default regeneration of MMOCORE regen , just a friendly reminder.

**Comment by Indyuce** [comment]
MMOItems uses the `EntityRegainHealthEvent` to apply the regen stat. I have checked on a server with Essentials & the latest version of MI and the regeneration just seems to work fine. Holding a +100% regen tome, I debug'd the event regain amount and got this:
[https://i.imgur.com/jbkwLxT.png](url)

**Comment by Indyuce** [comment]
Closed till further info is provided
