### ISSUE TITLE
Use mods items with catserver

### ISSUE THREAD

**Issue by SparkGNRK** [Indyuce/mmoitems#41]
I use catserver to support forge mods with spigot plugin (catserver is a fork of spigot like cauldron but very stable), when i want to use an item of a mod (like custom npc or variedcommodities) MMOItems say that this is not a valid material ID (i've tried an old id like '179', variedcommodities:diamond_greataxe and DIAMOND_GREATAXE). The plugin work very good and not make error at all in catserver.

**Describe the solution you'd like**
Can be able to use external material id. (all other plugin i have work good with mods item like chestcommands)

![2019-08-25_21 20 54](https://user-images.githubusercontent.com/50796872/63654779-44c44c00-c77f-11e9-9f78-19651bf4c126.png)

**Comment by Indyuce** [comment]
Added to Trello. Adding support for mods if not our top priority tho.

**Comment by SparkGNRK** [comment]
I know but thanks for your answer! The plugin work perfectly if i don't use mods items ^^ have a good night
