### ISSUE TITLE
Error in console when trying to view Silver Ingot crafting recipe

### ISSUE THREAD

**Issue by cloakfox** [Indyuce/mmoitems#44]
![Knipsel](https://user-images.githubusercontent.com/3696645/63978439-a275d280-cab6-11e9-82ea-13899f39458b.PNG)

https://pastebin.com/dmNuJsJj

Using MMOItems 4.7.13
Using PaperSpigot 1.13.2

**Comment by Indyuce** [comment]
Please send the required item configs so I can reproduce this issue on my end. This includes the config of that Silver Ingot item **plus** the configs of the items used as ingredients in this item recipe.

**Comment by Indyuce** [comment]
Will be fixed in the next update. If you'd like to fix the issue on your end please read what I said in the most recent ticket related to that issue: https://github.com/Indyuce/mmoitems/issues/45
