### ISSUE TITLE
Unable to extract legacy-configs.zip [MMOItems 4.7.14]

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#46]
**Describe the bug**
A folder bug, unable to extract or even view contains in legacy-configs.zip

**Screenshots**
https://imgur.com/a/oJH8qM5
![image](https://user-images.githubusercontent.com/54104726/64064224-12a86380-cc31-11e9-9dc2-b4d82f394509.png)

**Plugin info:**
 - Plugin Version: MMOItems 4.7.14

Sorry to say that, i'm here to report bug **again**. I'm kinda easy to trigger bug, same goes as other plugin :/

**Comment by Indyuce** [comment]
Will be fixed in the next update.

**Comment by Arkhtencial** [comment]
Thank you so much.
