### ISSUE TITLE
Attack Speed Modifier bug

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#47]
**Describe the bug**
As you know, minecraft from 1.9 start to having "cooldown" on attack, if your cooldown wasn't ready you deal nearly no damage at all. Now the happen is, my weapon is always in "cooldown" status, below is a gif to describe it.

**GIF**
https://imgur.com/a/1gMr1Cb

**To Reproduce**
1. Attack entity does base damage (around 2.1), due to "item in cooldown".
2. No console debug log or whatsoever.
3. This bug only apply to Melee weapon.
4. Neither attack speed is "positive value" 0.9,1.1,2.33 or "negative value" -0.1,-0.33,-1.8 still having the same bug.

**BUT**
Weapon speed with 10 or above having no issue, but player can nearly spam-click and kill everything in their sight.

**Server info:**
 - SPIGOT-1.12.2-R0.1-SNAPSHOT
 - MMOItems v4.7.14

**Additional context**
1.Tried a clean spigot installation (only mmoitem as plugin), still buggy.
2. Tested client version from 1.12.x up till 1.14.4, still having the same bug.
3. Called some friend to test it (along with 2 method above), still buggy.

**Server file needed to debug?**
If you needed.

**Comment by Indyuce** [comment]
Works fine on my end, spigot 1.14.4 build. Using this item to test and I have the right amount of attack speed based on the output I have using `/mi checkattribute generic_attack_speed`:
```
SILVER_SWORD:
  material: IRON_SWORD
  name: '&fSilver Sword'
  attack-damage: 6.0
  attack-speed: 1.6
  lore:
  - '&7May be upgraded.'
  required-level: 4.0
```

![javaw_gIHqNbsgWp](https://user-images.githubusercontent.com/29358517/64079129-11843e80-cce4-11e9-994a-f505987df141.png)

**Comment by Arkhtencial** [comment]
![image](https://user-images.githubusercontent.com/54104726/64079906-6ba2f500-cd20-11e9-8e6c-8ebfa9f6f531.png)
![image](https://user-images.githubusercontent.com/54104726/64079910-7f4e5b80-cd20-11e9-90c7-31c7664bbc30.png)


Too bad, this is what i get, when holding that particular item.

**Comment by Arkhtencial** [comment]
Instead, this is the value i get while holding "Regular Diamond Sword"

![image](https://user-images.githubusercontent.com/54104726/64079981-45318980-cd21-11e9-951d-77c20e42a748.png)

**Comment by Arkhtencial** [comment]
![image](https://user-images.githubusercontent.com/54104726/64081265-2b983e00-cd31-11e9-8d32-6f430658d274.png)

![image](https://user-images.githubusercontent.com/54104726/64081270-39e65a00-cd31-11e9-9529-8f1b852c52d8.png)

**Value bug found**
As i'm testing the attack speed value (yes i'm testing it i from the past 2 hours), i found an intreasting outcome when i set its attacking speed to 3. And somehow it works now, it have fine attack "cooldown" animation, just anyway to get rid of this bug? As i don't want my player see "Attack Speed 3" but it's actually a 0.6 attack speed.

**Comment by Indyuce** [comment]
Again, changing the item atk. speed to 3 works fine on my end. Make sure this issue is not caused by any other server mod or plugin.

**Comment by Arkhtencial** [comment]
Tested with 1.13 and 1.14 no problem, the problem only within version 1.12.2

**Comment by Indyuce** [comment]
I believe Aria has fixed that issue by now.
