### ISSUE TITLE
RacesAndClasses mana support

### ISSUE THREAD

**Issue by SparkGNRK** [Indyuce/mmoitems#50]
**Is your feature request related to a problem? Please describe.**
I use RacesAndClasses plugin for my RPG server, I'm on 1.12.2 version and I use feature that no other plugins (supported by MMOItems) have, like Berserker trait (modifies your damage, when your health is below 30%) and I need to use the mana system from this plugin.

**Describe the solution you'd like**
I want MMOItems hook into this plugin (like for heroes or skillapi) to be able to use customs items with this mana system.

**Additional context**
Use a elve race (+10% of mana regen per seconds) and mage class (+200 Mana points) and be able to use this mana to use custom items with needs of mana.

Thanks for the best custom items plugin and have a good day ! ^^

**Comment by Indyuce** [comment]
Will be added
