### ISSUE TITLE
Item Upgrades not working as expected. [minor bug]

### ISSUE THREAD

**Issue by iMxAndyy** [Indyuce/mmoitems#52]
The message the player recieved when an upgrade fails is the same regardless of what settings are selected for upgrades. The message states that the upgrade failed and they lost the consumable. but it says that even if the crafting recipe upgrade was used (which does not use a consumable) and it even says that if the item breaks and does not say anything about the item breaking. 

Also toggling the consumable upgrade/crafting recipe upgrade doesn't seem to do anything. both upgrade types still work regardless of what is selected. as well as any upgrade consumable working regardless of their upgrade reference matching.

**Comment by Indyuce** [comment]
I'd like to apologize for the delayed answer.

Are you still having that issue? If so please paste the item/upgrade templates/crafting stations configs you used to reproduce the issue. Thanks

**Comment by Indyuce** [comment]
Closed till further info is provided
