### ISSUE TITLE
Different Item Stats for Different User Permissions for 1 item.

### ISSUE THREAD

**Issue by pinkpig3777** [Indyuce/mmoitems#55]
**Is your feature request related to a problem? Please describe.**
It sucks that if I'd like to implement this idea currently, as far as I know, I need to create two items that are almost identical but one requires a different permission than the other and has slightly different stats. I'd like to be able to create a single item that has different stats/abilities for players with different permissions.

I want all players to be able to create all custom items but some of those items will have different stats depending on the player using it. This would be done using permissions. For example, let's say the "Obsidian Sword" has a special ability performed whenever used by a player with mmoitems.sword.obsidian.use.normal. However, if someone with the permission: mmoitems.sword.obsidian.use.special uses the sword (instead of the .normal permission), then the player will be able to use a slightly better version of that special ability and will have slightly different lore. 

Currently, as far as I am aware, if I wanted to make this happen I would need to create 2 items that look near identical but require the different permissions to craft & use, and give slightly different abilities. This is very time consuming if using the in-game editor and has the downside that if a player with the .special permission tries to use someone else's sword with the .normal permission, those are actually two different items and thus the player won't be able to use the item at all because they don't have the .normal permission.

**Describe the solution you'd like**
Explained above.

**Describe alternatives you've considered**
- I've gone through a lot of scenarios in my head of ways around this or alternative methods that allow the same type of idea. This is the best I've come up with. I want all players to be able to use all custom items on my server but for players in a specific class, they will be able to use specific items with slightly better stats than when used by other classes. Thus everyone can enjoy all custom items, but specific classes will get slightly better perks for specific items.

**Additional context**
None that I can think of.

Hope you'll consider this or let me know how to do it if it already is. Thanks!

**Comment by pinkpig3777** [comment]
I also posted this here:
https://www.mythicmobs.net/index.php?threads/different-item-stats-for-different-user-permissions-for-1-item.9509/

**Comment by Indyuce** [comment]
This is a very specific feature and making items not behave the same based on permissions would not be worth the time spent on implementing this. I've thought about adding **conditional** stats (stats that would only applied if a certain player condition is met), which is essentially not exactly what you're talking about but this could be used to approach what you're trying to get. However this is a very heavy mecanism and it will require quite a few plugin code refactors
