### ISSUE TITLE
MMOitems version 4.7.19b dont work with the Hook of RPG Player Leveling 3.9.30

### ISSUE THREAD

**Issue by MrRichfield** [Indyuce/mmoitems#56]
**Describe the bug**
I have a fresh spigot server with straight times 4 plugins and notice that the integration with RPGPlayerLeveling does not really work. I have not changed anything until the drop rate of a predefined monster is set to 80%. The killing goes without problems. only when I am collecting or using the item does it flooded the console.

**To Reproduce**
1. Download the following Spigot Serverfile from https://getbukkit.org/get/QMerkBxNGNl3EnQl8gACGfWuJnJtJuWB and setup a fresh Spigot 1.13.2 Server
2. Attack entity... and Collect the Drop or use it etc
4. See console log...

**Expected behavior**
It should work with the called plugin without problem

**Server info:**
 - CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - MMOitems 4.7.19b
 - Plugins: that could called the issue MMOItems, HolographicDisplays, Vault, RPGPlayerLeveling

**Additional context**
When i Remove the Plugin RPGPlayerLeveling it works without Problems. but i need RPGPlayerLeveling to increase the Health by levelup..

**Comment by MrRichfield** [comment]
So i Update to the dev Build of MMOitems version MMOItems-5.1-SNAPSHOT.jar the same error occurs when i killed a mob and collect a drop it spams the console

**Comment by MrRichfield** [comment]
here is the content of the latest.log
[latest.log.txt](https://github.com/Indyuce/mmoitems/files/3855175/latest.log.txt)

**Comment by Indyuce** [comment]
RPGInventory was abandonned a while ago. While this issue can potentially be fixed with some rewriting, I'm not willing to invest my time fixing support for outdated and abandonned plugins. I may fix it in the future if I come up with a quick fix but it's not a top priority.
