### ISSUE TITLE
I can't even do /mi reload now?

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#59]
**Describe the bug**
Well, i can't even do /mi reload

**GIF**
![Bug_1](https://user-images.githubusercontent.com/54104726/70395476-03a82d00-1a3a-11ea-9e24-83728969aa88.gif)

**Server info:**
SPIGOT-1.12.2-R0.1-SNAPSHOT
MMOItems v5.1.1

**Additional context**
Tried a clean spigot installation (only mmoitem as plugin), the result is still the same.

**Comment by Indyuce** [comment]
Closing since most likely fixed in latest builds
