### ISSUE TITLE
Custom Durability invalid BUG

### ISSUE THREAD

**Issue by yusisi08** [Indyuce/mmoitems#62]
Hello I am a Chinese, English is not very good, I am invalid when using the custom durability of the plug-in, the plug-in will not be calculated, it is still the original durability of MC
I want to know why   ？？？

Here is the picture
https://sm.ms/image/lFPxepoY5QjCWM1

**Comment by Indyuce** [comment]
Check out the custom durability wiki page:
https://github.com/Indyuce/mmoitems/wiki/Custom-Durability

Additional Note: custom durability is getting revamped in the next update. It will be made much less confusing and much more performance friendly
