### ISSUE TITLE
On the problem of placing block on the left hand.

### ISSUE THREAD

**Issue by killertuling** [Indyuce/mmoitems#63]
hello. I am a Chinese.
So my English is not very good.
I'll try to describe my problems to you.

I find that when I use some consumables,If this consumable is a placeable block,such as rock,burger(playerhead).
When I put them on my left hand,And then I found out that they could place.
then I break it and pick it up,It will not work and be a common block.

please fix it! thanks!

**Comment by Indyuce** [comment]
You can enable the _Disable Interaction_ item option to prevent players from placing blocks
