### ISSUE TITLE
Mana

### ISSUE THREAD

**Issue by UnitedSlayer** [Indyuce/mmoitems#64]
**Describe the bug**
The bug is the Max Mana Attribute.
When changing the max mana it doesnt change anything
Even when in /mi info it still says mana is 20
**To Reproduce**
1. Enable option...
2. Attack entity...
3. Create item...
4. See console log...

**Expected behavior**
Id expect to either lower the rate at which hunger is lowered or increase hunger bars
**Screenshots**

**Server info:**
 - Spigot Build & Version 
![image](https://user-images.githubusercontent.com/13069633/72672067-b5b41b00-3a22-11ea-99dc-c91577c62c30.png)

 - Plugin Version 5.2.1
 - Potential plugins linked to the issue

**Additional context**
Is this feature restricted to MMOCore?

**Comment by Indyuce** [comment]
Mana is restricted to other RPG plugins as MMOItems does not come with a built in mana system. Therefore, you may either use a RPG core plugin like MMOCore or Heroes, or download the official MMOItems [mana/stamina addon](https://www.mythicmobs.net/index.php?resources/mmoitems-manaandstamina.145/) over the MythicCraft forums.
