### ISSUE TITLE
Back Button in AdvancedWorkbench

### ISSUE THREAD

**Issue by pandory-network** [Indyuce/mmoitems#65]
**Describe the bug**
The Back Button in AdvancedWorkbench produce an error Click Event

https://gist.github.com/pandory-network/81dbe39b37c7a8d46fff78693ee0450d

**Server info:**
 - Latest Paper Server Version
 - MMOItems Premium 5.2.1

**Comment by Indyuce** [comment]
Closing this ticket since the AWB was removed in the latest builds.
