### ISSUE TITLE
[Feature] Object link only for the player when took or when used

### ISSUE THREAD

**Issue by Tiplish** [Indyuce/mmoitems#66]
Hi ! 

I'm not sure if this feature already exist but i think that be able to link an object to the player could be a usefull add. 

First case : The player get the object (craft/loot/pick,...) and the object is directly link to him. Nobody else could use it.
Second case : The player get the object (craft/loot/pick,...). If the player equip or use it, it becomes linked to the player.

**Comment by Indyuce** [comment]
We do have a feature similar to that, it's called Soulbound
https://github.com/Indyuce/mmoitems/wiki/Soulbound

**Comment by Tiplish** [comment]
It's not exatcly this. Soulbound link don't link to the player when he use it for example. 

And another player could break the link if he has the right object.
