### ISSUE TITLE
[Bug] Damage reduction doesn't apply on ability

### ISSUE THREAD

**Issue by Tiplish** [Indyuce/mmoitems#68]
**Describe the bug**
Hi ! 

When i try to reduce ability damage on an armor, the option "Damage reduction" doesn't apply. There is no "ability damage reduction" either. 

**To Reproduce**
1) Get an item with 50% reduction of all sources
2) Use a ability to inflict damage
3) The ability inflict full damage instead of 50%
**Expected behavior**

**Server info:**
- This server is running CraftBukkit version git-Spigot-492a779-fde78ef (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
 - MMOItems 5.2.1

Any help ?

**Comment by Zacushka** [comment]
Tiplish, is damage reduction on the armor or you weapon?  It doesn't reduce damage casting it reduces damage taken when applied to armor.

**Comment by Tiplish** [comment]
It's on the armor. How i could reduce spell damage with a stats on the armor ?

**Comment by Indyuce** [comment]
There is no option to reduce skill damage taken atm however this can be easily added given MMOCore stat system. The damage reduction bug should be hopefully fixed in the latest MI dev build.

**Comment by Tiplish** [comment]
so, don't reduce damage from ability with the reduce damage is a bug or a normal feature ? ^^'

**Comment by Indyuce** [comment]
There was an issue with damage reducing stats which appeared with the MMOCore transition and which we weren't aware of, should be fixed in the latest MMOItems dev build.
