### ISSUE TITLE
MMOi v5.2.1 | (Most of the) abilities not working correctly in 1.12.2

### ISSUE THREAD

**Issue by Ghmmy** [Indyuce/mmoitems#69]
**Describe the bug**
When I bind an ability to an item and try to use it, it hands out warmings/error in the console. I am aware that I have to bind it to an action like ON_HIT or RIGHT_CLICK. It is not that all abilities dont work, just a hand full of them, which annoys me a lot since the spigot page states that it is 1.12 compatible and for the price I paid I expected it to work correctly. 

Some of the abilities, like Blink or Starfall only make the sounds/particles and nothing else. Abilities like Black Hole and Bouncy Ball do absolutely nothing. I would love to see this issue fixed as it causes many troubles for the people who are still running on 1.12. Switching to 1.15 wont be a solution for this problem as our entire network consists of 5 servers with all around 60 plugins which most of them are only compatible for 1.12. Switching to 1.15 means we have to reupload roughly 500 plugins and sadly for our small staff team is that a no-go. 

**To Reproduce**
1. Bind an ability to an item created with the /mi browse
2. Add the action to it, such as RIGHT_CLICK.
3. Get the custom item
4. rightclick the enemy
5. the animation/ability wont play.
6. if you want to rightclick again, it would tell you that the ability is on cooldown (which is in fact correct as the ability should have cast)
Bonus: The console spits out around 20 WARNs every second.

**Expected behavior**
For the Blink ability I excepted the player to be teleported x blocks further away from his original location as tested on  the legacy version of MMOitems where it did work as intended.
For the Black Hole ability I expected the mobs getting sucked into the location the player was currently looking at. But upon rightclicking, the mobs, that were like 2 blocks away from that position, didnt get sucked into the location.

**Screenshots**
Blink ability on cast: 
![image](https://user-images.githubusercontent.com/58144601/73969486-cc5fda80-491b-11ea-9ce6-06a525ac3f05.png)

Blink ability after cast:
![image](https://user-images.githubusercontent.com/58144601/73969513-df72aa80-491b-11ea-8a56-66d215c03f90.png)

Console errors/warns:
06.02 19:42:37  [Server]  WARN Task # 2359 for MMOItems v5.2.1 generated in exception 
06.02 19:42:37  [Server]  INFO java.lang.NoClassDefFoundError: Could not initialize class net.mmogroup.mmolib.version.VersionSound 
06.02 19:42:37  [Server]  INFOat net.Indyuce.mmoitems.ability.onhit.Starfall $ 1.run (Starfall.java:45) ~ [MMOItems-5.2.1.jar:?] 
06.02 19:42:37  [Server]  INFO at org.bukkit.craftbukkit .v1_12_R1.scheduler.CraftTask.run (CraftTask.java:76) ~ [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFO at org.bukkit.craftbukkit.v1_12_R1 .scheduler.CraftScheduler.mainThreadHeartbeat (CraftScheduler.java:361) [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFO at net.minecraft.server.v1_12_R1.Minecraft D (MinecraftServer.java:739) [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFOat net.minecraft.server.v1_12_R1.DedicatedServer.D (DedicatedServer.java:406) [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFO at net.minecraft. server.v1_12_R1.MinecraftServer.C (MinecraftServer.java:679) [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFO at net.minecraft.server.v1_12_R1.MinecraftServer .run (MinecraftServer.java:577) [Spigot1.12.2_plain.jar: git-Spigot-79a30d7-acbc348] 
06.02 19:42:37  [Server]  INFO at java.lang.Thread.run (Thread.java:748) [?: 1.8.0_242] 
(this is just one of the thousands of warns it generates per second)

**Server info:**
SERVER VERSION:
- 1.12.2
PLUGIN VERSIONS:
- MMOitems v5.2.1
- MMOlib v1.0.6
- MMOitemsLegacyWG v1.1.1
- Worldguard v6.2.2-snapshot

I would love to see this issue solved, as the plugin wasnt **that** cheap and on the spigot page it says that 5.2.1 is still compatible with 1.12 (5.3 will no longer support 1.12). Plus I havent had any issues with all the other features it offers, which is a good thing. :^)
If you need more information about this issue, please inform me so I can help you out.

Kind regards,

Ghmmy, a slightly disappointed customer

**Comment by Indyuce** [comment]
There was a bug with the 1.12 sound names we were using for legacy. Will be fixed in the next version of MMOLib
