### ISSUE TITLE
MMOItems custom skill damage placeholder will not read

### ISSUE THREAD

**Issue by Zacushka** [Indyuce/mmoitems#71]
**Describe the bug**
The placeholder <mmoitems.skill.skillname.damage> does not translate in mythic mobs.  This placeholder is listed on the wiki and is VERY important with making new skills.

**To Reproduce**
1. Enable option...
shadowbolt:
 
  Skills:
  - jsonmessage{m="[{'text':'test <mmoitems.skill.shadowbolt.damage>'}]"} @Self
  - message{m="test <mmoitems.skill.shadowbolt.damage>"} @Self

ALL REFERENCES TO THE SKILL HAVE BEEN COPIED AND PASTED SO THERE IS NO QUESTION OF NAME FORMAT.  

I have also made sure to assign damage to the actual item casting the skill.  I've gone through the discord support first before reporting.

I tested mmocore and it works fine with mmocore.skill.name.damage

Here is a reference to the MMOItems placeholder on your wiki https://github.com/Indyuce/mmoitems/wiki/Abilities

2. Attack entity...

I this is just my debug action.

![image](https://user-images.githubusercontent.com/59065830/74163500-7a0b0c00-4bf0-11ea-85b4-f4944284ebdc.png)

3. See console log...

https://pastebin.com/mEPETxXR

**Expected behavior**

I expect an integer return for the placeholder so I can use the same skill with progression.

**Screenshots**

**Server info:**
 - Spigot Build & Version
paper-spigot 1.14.4 v243 (final build)
 - Plugin Version
MMOItems 5.3
MMOlib 1.0.6
Mythic mobs 4.8.0

 - Potential plugins linked to the issue
mythic mobs 
**Additional context**
Might just want to test it out yourself.  Shouldn't be hard.

**Comment by Indyuce** [comment]
Can you give the latest dev build a try? There was indeed an issue with MMOItems placeholders which I just fixed

**Comment by Zacushka** [comment]
Fixed as of 5.3.2 build 125. Ty
