### ISSUE TITLE
[bug] Spells suppose to apply only on ally work on ennemies

### ISSUE THREAD

**Issue by Tiplish** [Indyuce/mmoitems#72]
Describe the bug:
Hi !

I'm trying to make spells which works only on ally but it seems that, if the target is ennemy or ally, the heal spell apply. 

Is it a normal behaviour ?

Thanks

Server info:

This server is running CraftBukkit version git-Spigot-492a779-fde78ef (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
MMOItems 5.2.1

**Comment by Indyuce** [comment]
It depends on the skill you are using. _Regen Ally_ only applies on players, _Heal_ can also heal monsters.

**Comment by Tiplish** [comment]
Ok i've my answer thanks :)
