### ISSUE TITLE
Crafting Station Item-ID and custom name not working in 1.12

### ISSUE THREAD

**Issue by Ghmmy** [Indyuce/mmoitems#75]
**Describe the bug**
When I want to add a color to a dye or a glass pane, it will throw out errors in the console telling it cant find that item. In 1.15 it works fine, but not in 1.12. When I try using BLACK_STAINED_GLASS_PANE or the no-queue material and set the name to '&cNo queue item', it wont work. the black glass pane will throw out an error, changing the data value by adding a :15 to it also will throw out errors. If I change the name with a valid item, like STONE_BUTTON, the stone button will still be named 'Stone Button' in-game (but doesnt throw out any errors). Please note that this in 1.12 only, it works correctly in 1.15. 

**To Reproduce**
1. Change material: STAINED_GLASS_PANE to material: BLACK_STAINED_GLASS_PANE (BLACK can be any color) or GRAY_INK_SACK (GRAY can be any color, the item ID for the DYE is INK_SACK in 1.12)
2. save the file and upload it to the server
3. reload the stations using /mi stations reload
4. it will say in-game that no are stations loaded and the console will spit out an error saying it cant find that material.

**Expected behavior**
In 1.15, it will change to the color it has infront of the _STAINED, in 1.12 this clearly isnt the case. same applies to DYE/INK_SACK

**Screenshots**
![image](https://user-images.githubusercontent.com/58144601/75352810-9d99ac00-58aa-11ea-844b-0254d2c31e38.png)
![image](https://user-images.githubusercontent.com/58144601/75352947-d8034900-58aa-11ea-8ca9-02821087aa8d.png)

![image](https://user-images.githubusercontent.com/58144601/75352871-b99d4d80-58aa-11ea-9546-71b665922dd7.png)
![image](https://user-images.githubusercontent.com/58144601/75352910-c91c9680-58aa-11ea-91a0-d080598ac8d2.png)

**Server info:**
 - Server version: 1.12.2
- MMOitems: 5.3.2
- MMOLib: 1.0.8
- MMOitemsLegacyWG: 1.1.1

**Additional context**
-

**Comment by Indyuce** [comment]
`BLACK_STAINED_GLASS_PANE` is for 1.13+ where they now have a unique material for every colored glass pane. Since you're running 1.12 you will need to use `STAINED_GLASS_PANE` with some specific durability/data which corresponds to the color you want

**Comment by Ghmmy** [comment]
Like I said in my describtion, changing the data/dura also doesnt work. 

> "the black glass pane will throw out an error, changing the data value by adding a :15 to it also will throw out errors."
