### ISSUE TITLE
[Bug] can't disable custom recipe

### ISSUE THREAD

**Issue by Tiplish** [Indyuce/mmoitems#77]
**Describe the bug**
Hi !

I've just migrate my server to the last version of MMOItems and i've a bug.
Custom recipes replace vanilla recipe despite i've change this parameter : 
disable-craftings: true

**Expected behavior**
Get only the vanilla recipe.

**Server info:**
 - git-Paper-120
 - MMOItems 5.3.2
 - MMOLib 1.0.8

Any help ? maybe i'm miss something. I've already try the command  /mi update apply 3 3

**Comment by Indyuce** [comment]
Should be fixed in the latest dev build

**Comment by survetman** [comment]
Hello ! 
We have this configuration:

Server info:

- git-Paper-229
- MMOItems 5.4.1
- MMOLib 1.1.2

I detect that this problem comes back. Vanilla crafts are replaced by Customs craft even if we have this: disable-craftings: true
