### ISSUE TITLE
Add eat to disable-interactions in config.yml

### ISSUE THREAD

**Issue by Daxxas** [Indyuce/mmoitems#8]
**Is your feature request related to a problem? Please describe.**
Change the actual disable-interactions of config.yml to add the eat feature in it
*(I don't know how to do multi line code example in github)*
disable-interactions:
    repair: true
    enchant: true
    smelt: true
    craft: true
    arrow-shooting:`false

**Describe the solution you'd like**
disable-interactions:
    repair: true
    enchant: true
    smelt: true
    craft: true
    arrow-shooting: false
    eat: true
Maybe have the config like this ?

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by Indyuce** [comment]
Sure, I'll add that.

**Comment by Indyuce** [comment]
You can already do that using an item option, I'm not sure a config option for that would be really useful
