### ISSUE TITLE
Gemstones - Skull texture loss

### ISSUE THREAD

**Issue by Ghmmy** [Indyuce/mmoitems#80]
**Describe the bug**
When you apply a gemstone to an item that has a skull texture (for example a spider texture), the gemstone will apply to the item, but the item would lose its texture and becomes a skeleton skull (1.12 skull_item ID). We wont change server versions.

**To Reproduce**
1. Get on a 1.12 server
2. Make/Get yourself a gemstone
3. Get youself an item that has a custom head texture (making it in the GUI: ID: skull_item DATA: 3 Head value: anything valid)
4. Apply the gemstone to the head in survival
5. The gem should bound, but the head will lose its texture

**Expected behavior**
The head texture should stay the same and not become a skeleton skull (default skull_item)

**Screenshots**
https://imgur.com/a/1namgDZ

**Server info:**
 - Server Version: 1.12.2
 - Plugin Versions:
MMOitems: 5.3.2
MMOitemsLegacyWG: 1.1.1
MMOLib: 1.0.8

**Comment by Indyuce** [comment]
It will be fixed in the next MMOItems spigot release

**Comment by Ghmmy** [comment]
I heard from other staff member in the discord that the latest version does not support 1.12 anymore. When I updated the plugin a few days ago, it kept throwing errors and the plugin did not start. Maybe bc some files got changed after the update and need some cleaning, or it just doesnt support 1.12 anymore. Can you please confirm?

**Comment by Ghmmy** [comment]
yea nvm
