### ISSUE TITLE
Citizens NPC hit-detection

### ISSUE THREAD

**Issue by CPieter** [Indyuce/mmoitems#81]
MMOitems doesn't seem to register npc collisions.

When I attack citizens npcs they are hit by the default item's attack, but abilities and custom attack types won't go off. 
I would like players on my server to be able to use these MMOitems on my npc guards.

My server is running on the latest spigot 1.15.2 build with:
- MMOitems 5.3.2
- Citizens 2.0.26
- MMOlib 1.0.9
- Sentinel 2.0.1 (The citizens addon I use for my guards)

**Comment by Indyuce** [comment]
I need to patch something over MMOLib, that will be fixed asap

**Comment by Indyuce** [comment]
Should be fixed in the latest build of MMOLib
