### ISSUE TITLE
re-add support for Mythic Mobs in the drops.yml

### ISSUE THREAD

**Issue by iMxAndyy** [Indyuce/mmoitems#84]
**Is your feature request related to a problem? Please describe.**
The problem is that I previously had Mythic Mobs setup and the drops were handled by MMOItems. 
This appears to have been removed and is now managed by Mythic Mobs. But the Mythic Mobs drops functionality is really bad. MMOItems allows for subtables that allow for 1 item drops each with their own drop rates. MM supports 1 item drops but setting it up required a lot more work and the drop rates are not per item. All drop rates are directly impacted by the rate of the item above it in the config meaning once you get past 2-3 items, there is basically 0 chance of an item dropping no matter what rate you set. 

**Describe the solution you'd like**
Re-add support for Listing Mythic Mobs in the drops.yml file so we can take advantage of MMOItems superior drop functionality.

**Comment by Indyuce** [comment]
Will be probably handled by an addon

**Comment by Flirtey** [comment]
@iMxAndyy I believe theres some misunderstandings on how you are setting up MythicMobs drop tables, Mythicmobs drop tables are far superior and I am happy to help you out.
