### ISSUE TITLE
Can't put gems on items with gem sockets.

### ISSUE THREAD

**Issue by Sotlol1** [Indyuce/mmoitems#85]
**Describe the bug**
Can't apply gems to weapons

**To Reproduce**
1. Start the server on 1.15.2 Paper,
2. Get a MMOitems sword
3. Try to apply a gem by dragging it on the sword
4. See errors in the console

**Server info:**
 - Spigot Build & Version: Paper 1.15 (Build 171)
 - Plugin Version: 5.3.2
 - Potential plugins linked to the issue MMOitems and MMOlib

**Additional context**
https://pastebin.com/X4GjA8ae My console error.

**Comment by Indyuce** [comment]
Don't use the latest spigot MMOLib build unless you are running MMOItems and MMOCore dev builds. Downgrade to 1.0.9
