### ISSUE TITLE
[Feature request] Add flat value for damage add or reduction

### ISSUE THREAD

**Issue by Tiplish** [Indyuce/mmoitems#86]
**Describe the solution you'd like**
Hi,

For the moment, i've just seen % damage modifier. I would like to use flat modifier. 
For example, instead of adding 10% physical damage,  i add 10 damages.
**Describe alternatives you've considered**
I've try to thin about a % which increase thanks to the level of the object but it becomes very complicated to maintain. 

I've seen that it works for flat damage of a weapon, but not such a feature for damage reduction or skill damage.

Thanks.

**Comment by Indyuce** [comment]
Added to Trello
