### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by Sotlol1** [Indyuce/mmoitems#87]
Is it possible to set the durability over 1561? 

I tried setting the durability of one of my times to 3000 but it's just breaks and makes the item unbreakable. (Unbreakable is False on the item) 

Version: 5.3.2 MMOITEMS, 1.0.9 MMOLIB
Server: 1.15 PaperMC

**Comment by Indyuce** [comment]
Custom durability would help you do that. Make sure you toggle on the _Lost when Broken_ option so that the item is lost if it reaches 0 durability (and so that it does not stay in your inventory till you repair it).

**Comment by Sotlol1** [comment]
Lost when broken is already turned on.

**Comment by Indyuce** [comment]
Please paste the item config you used to reproduce that issue

**Comment by Sotlol1** [comment]
So which one of them should be used? Max or none max?

**Comment by Indyuce** [comment]
The one you are looking for is probably `Max Durability`, you'll need to set the other one to 0.

**Comment by Sotlol1** [comment]
Okey! This is the config I have for the item that isn't working correctly.

'3':
  material: DIAMOND_SWORD
  custom-model-data: 3.0
  name: '&8Obsidian &fSword'
  max-durability: 3000.0
  disable-repairing: false
  disable-enchanting: false
  disable-smelting: true
  disable-crafting: true
  attack-speed: 1.6
  attack-damage: 6.0
  will-break: true
  lore: []

**Comment by Indyuce** [comment]
The item you provided seems to behave normally on my end, I tried setting max durability to 10 and it would break after I hit a zombie 10 times.

**Comment by Sotlol1** [comment]
Yeah exactly. They all work when putting them at something below 1561. But if you put them over that they can't break. I have had a moderator try to break a 3000 durability item for 5 days now without any mending or unbreaking enchantment and there isn't even a dent on it.

**Comment by Sotlol1** [comment]
From the update yesterday the sword started losing durability like intended. Even though nothing was mentioned about it haha. So it's working now.
