### ISSUE TITLE
Identify item GUI

### ISSUE THREAD

**Issue by titidelaff** [Indyuce/mmoitems#88]
It would be nice to have a GUI to be able to identify the items.
We insert the unidentified object in a slot then we validate via a button (against money, item, etc.).
Result we get our identified item.
On the same principle as on the Wynncraft server basically.

![image](https://user-images.githubusercontent.com/23405363/79570510-d93a4080-80b9-11ea-9dce-855387911c3d.png)

**Comment by Indyuce** [comment]
Already on Trello
