### ISSUE TITLE
CustomModelData in item-types.yml

### ISSUE THREAD

**Issue by jeannen** [Indyuce/mmoitems#9]
**Describe the solution you'd like**
That wouldbe cool if we could change the CustomModelData (and/or Durability) from the item-types.yml, that way we would have a more accurate /mmoitems browse and it would avoid manually changing the Model Data ID everytime we create a new item

**Comment by Indyuce** [comment]
Sure

**Comment by Indyuce** [comment]
Will be implemented in the next update, clossing the ticket
