### ISSUE TITLE
Dynamic Modifiers/Attributes

### ISSUE THREAD

**Issue by Ghmmy** [Indyuce/mmoitems#92]
**Is your feature request related to a problem? Please describe.**

I am frustrated with the fact that we cannot deal damage compared to statistics of a player. (deals 50% of your current health or deals twice the damage of your balance, using the maths placeholder)

**Describe the solution you'd like**

Support PlaceholderAPI's placeholders in the (damage) modifiers/attributes, so players can deal damage accumulated to their statistics. Lets say you set the damage of an item to 6. it would deal 6 damage. but if you set it to %player_max_health% instead of 6, it would deal damage accumulated to your health, so 20. but if you wear an armor piece with 6 extra health, it would deal 26 damage and so on. 
This wouldnt only apply to damage, but also stuff like damage reductions, crit chance and damage and other attributes with integers. 

**Describe alternatives you've considered**
Hook PAPI into MMOitems (or vice versa) so players can enter placeholders as attributes instead of only numbers.

**Additional context**

Damage modifers to specific mobs would also be nice to see, instead of only more damage to undeads. Like players can set the damage boost against mob A, B and C.

**Comment by Indyuce** [comment]
That would be pretty hard to setup, currently the way MMOItems is built would really not allow that to be implemented yet I'll add that to the Trello if I one day plan a MMOItems 2.0 update
