### ISSUE TITLE
Bossshop intergation not working

### ISSUE THREAD

**Issue by Darwin1546** [Indyuce/mmoitems#97]
**Describe the bug**
Looks like Bossshop intergation is not working.

>     RewardType: MMOITEM
>     Reward:
>     - CONSUMABLE.BUILDING_PERMISSION

I've tried RewardType and PriceType, nothing happens.

**Server info:**
 - Spigot Version: 1.14.4
 - Plugin Version: MMOItems Premium 5.3.2

**Comment by yerktoyn** [comment]
I confirm this problem

**Comment by Indyuce** [comment]
Will be fixed in the next MI dev build.
