### ISSUE TITLE
Update attack Damage value on enchant

### ISSUE THREAD

**Issue by Sotlol1** [Indyuce/mmoitems#98]
Would be nice to have the feature that the attack damage value gets updated when you enchant an item.

----------

![helyh](https://user-images.githubusercontent.com/6286246/80857886-d44ac480-8c55-11ea-8ad4-78afc45647d9.png)
Vanilla MC ^

![helyh2](https://user-images.githubusercontent.com/6286246/80857889-d6148800-8c55-11ea-8370-32abb0ae5a1f.png)
MMOitems^

**Comment by Indyuce** [comment]
Would require a **huge** stat rework that won't happen within the next months, but this could be implemented
